[package]
name = "gify"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
mime_guess = "2.0.5"
regex = "1.11.1"

[dev-dependencies]
rstest = "0.25.0"
